#! /bin/bash

# aliases
if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# .env variables
if [ -f ~/.config/.env ]; then
	source ~/.config/.env
fi

# init starship
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi

# uv
export PATH="/home/austin/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
