# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.5

# Cursor
cursor_shape     block
cursor_blink     on

# Window appearance
background_opacity 0.95
hide_window_decorations yes
tab_bar_style powerline

# Colors
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #cdd6f4
url_color               #f5e0dc
cursor                  #f5e0dc

# Normal colors
# black
color0  #45475a
# red
color1  #f38ba8
# green
color2  #a6e3a1
# yellow
color3  #f9e2af
# blue
color4  #89b4fa
# magenta
color5  #f5c2e7
# cyan
color6  #94e2d5
# white
color7  #bac2de

# Bright colors
# bright black
color8  #585b70
# bright red
color9  #f38ba8
# bright green
color10 #a6e3a1
# bright yellow
color11 #f9e2af
# bright blue
color12 #89b4fa
# bright magenta
color13 #f5c2e7
# bright cyan
color14 #94e2d5
# bright white
color15 #a6adc8

# Optional padding
window_padding_width 8

