# vim:ft=hyprlang


###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = yazi
$menu = walker
$statusBar = waybar

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Notification agent
exec-once = systemctl --user start hyprpolkitagent
exec-once = $statusBar
exec-once = walker --gapplication-service
exec-once = clipse -listen
exec = hyprshade auto
exec-once = udiskie
exec-once = hypridle
exec-once = hyprpaper

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

