preload = ~/Wallpapers/current/a_purple_and_orange_mountain_range.png

wallpaper = DP-1, ~/Wallpapers/current/a_purple_and_orange_mountain_range.png

wallpaper = DP-2, ~/Wallpapers/current/a_purple_and_orange_mountain_range.png
