################
### MONITORS ###
################

# monitor=,preferred,auto,auto
monitor=DP-1, 1920x1080, 1920x0, auto
monitor=DP-2, 1920x1080, 0x0, auto

########## APPS ##########

source = ~/.config/hypr/apps.conf
source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/variables.conf
