preload = ~/Wallpapers/current/a_blue_and_orange_background.jpg

wallpaper = DP-1, ~/Wallpapers/current/a_blue_and_orange_background.jpg

wallpaper = DP-2, ~/Wallpapers/current/a_blue_and_orange_background.jpg

